// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChhRCIJOVn8jqphAc2mgqlAnJWcANj35U',
    appId: '1:846627499392:web:45df1132021be944b76565',
    messagingSenderId: '846627499392',
    projectId: 'flatter-chat-52761',
    authDomain: 'flatter-chat-52761.firebaseapp.com',
    storageBucket: 'flatter-chat-52761.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWjeO9t2tknKkuqmpOKoALN0Ol78FqGos',
    appId: '1:846627499392:android:6802bf45e5476caab76565',
    messagingSenderId: '846627499392',
    projectId: 'flatter-chat-52761',
    storageBucket: 'flatter-chat-52761.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEmX0NhmXxFtBSx3g4wvGZDDtLUzqK7po',
    appId: '1:846627499392:ios:77866330e9943f4bb76565',
    messagingSenderId: '846627499392',
    projectId: 'flatter-chat-52761',
    storageBucket: 'flatter-chat-52761.appspot.com',
    iosClientId: '846627499392-mef4it72e34kr92d2ecb6tdmjqr722gu.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChat',
  );
}
